# Theme settings
doks:
    baseurl:
    color_theme: green # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: QOSF
            image:
        nav:
            - item_name: Home
              item_url: '/'
            - item_name: Manifesto
              item_url: '/manifesto'
            - item_name: Learn
              item_url: '/learn_quantum'
            - item_name: Code
              item_url: '/project_list'
            - item_name: Ranking
              item_url: '/ranking'
    footer:
        content:
            logo:
                text: Quantum Open Source Foundation </br> (QOSF)
                image:
            copyright: This website is itself open source and released under a CC0 license.
        social_list:
            - network_name: facebook
              profile_url: '#'
            - network_name: twitter
              profile_url: '#'
            - network_name: instagram
              profile_url: '#'
            - network_name: youtube
              profile_url: '#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
